
export const navbarLinks = [
  {
    imgURL: '',
    route: '/products',
    label: 'Shop',
  },
  {
    imgURL: '/icons/upcoming.svg',
    route: '/cart',
    label: 'Bag',
  },
  {
    imgURL: '/icons/upcoming.svg',
    route: '/favorites',
    label: 'Favorites',
  },
];

export const products = [
  {
    price: '$120',
    salePrice: '$100',
    salePrecent: '-$20',
    title: 'Cool Shoes',
    liked: false,
    rating: 4,
    ratingCount: 18,
    url: '/products/coolshoetitle',
  },
  {
    price: '$120',
    salePrice: '$100',
    salePrecent: '-$20',
    title: 'Cool Shoes',
    liked: false,
    rating: 5,
    ratingCount: 16,
    url: '/products/coolshoetitle',
  },
  {
    price: '$120',
    salePrice: '$100',
    salePrecent: '-$20',
    title: 'Cool Shoes',
    liked: false,
    rating: 3,
    ratingCount: 10,
    url: '/products/coolshoetitle',
  },
  {
    price: '$120',
    salePrice: '$100',
    salePrecent: '-$20',
    title: 'Cool Shoes',
    liked: false,
    rating: 2,
    ratingCount: 7,
    url: '/products/coolshoetitle',
  },
  {
    price: '$120',
    salePrice: '$100',
    salePrecent: '-$20',
    title: 'Cool Shoes',
    liked: false,
    rating: 4,
    ratingCount: 5,
    url: '/products/coolshoetitle',
  },
  {
    price: '$120',
    salePrice: '$100',
    salePrecent: '-$20',
    title: 'Cool Shoes',
    liked: false,
    rating: 4,
    ratingCount: 1,
    url: '/products/coolshoetitle',
  },
]